all:
    children:
        #ENC[AES256_GCM,data:Q4FeJtCoVsveFWptyJDpZiogb5QtdMIDRf8oIgzkfO9eYChCtrAAXItlDtiD52jMeppCkMKSLBq3oBD7,iv:yfqOf99tQA5MeZ7Qgf8jOe+19jxB2HNsXO+zFGkLxyA=,tag:f0bxQLc06cSF/PAqgz2R3A==,type:comment]
        #
        #ENC[AES256_GCM,data:lt1YaSwR1o0keQ96sw==,iv:S4OE+efdwgHgQFA97Ysy38eSxpMH9p4A4H8SNeip8qk=,tag:zRWsC5FuhJjST1R6DOCgeA==,type:comment]
        #
        #ENC[AES256_GCM,data:61cS8wAGOdsaRB0u91c/82oowlSda4o4JzMcap+8THcWExzov/MU+8uphPH0cMDeD3yDFCk+5BF5H1ua,iv:o5bVQggyDdwv906DMOBteCju6SARnEAoZ3B08sUXjC8=,tag:m+I2TbHeahWooNVmq/3YLw==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:Jx8eRYaXmGrpPJwzcA==,iv:pXymy6+HFrVud/Pv5H7I0X1//frOocpicaK6L9l3lJk=,tag:SKQovlw56pJ/I/hCsN4Wxw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:ns+mvfWIK5Y=,iv:RTFdybjLUSGNvtQE+jK/amMms9T5YMCyBQZJuwIPehM=,tag:fIfkaej11KIDIROa70Tz4A==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:UMAhxe5TilQJNsujvoNvIcU=,iv:1i6tt2l/kJCKkcPjB5xUsfkPuBkplNF3lp/mhg3Y/1M=,tag:74+7JIInhEJXe2hlPk6TgA==,type:str]
        installer:
            hosts:
                pi5-installer:
                    ansible_host: ENC[AES256_GCM,data:OIccjNKu4iD/pk8g,iv:YvPcdrhIkS+bLGLTNgHbBAkyJPghbgfmOqCuet7NH9I=,tag:/Yz4k3vFgGJFG4s2Ay2Aag==,type:str]
                    ansible_user: ENC[AES256_GCM,data:S7Si+vzvt6Q=,iv:6Y81GCn46eVrgpCumwa61EctQqXuWmAZ4TocQtjT02Q=,tag:qkSeGOebUlQwtqg7o5p+Ng==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:zPGe0d8R/oy19dubRcLfAFA=,iv:SPl/T9Z7U0sLCF1V3EKNEedm5DGfFQSAfp3lxsp5FHE=,tag:+wNvVGcP+DXm+2w/HHNgPw==,type:str]
        #ENC[AES256_GCM,data:/b4t9YsllHrxeCa4kzwxFXGjr5nIhWge3KrB0fEjhbnzDcIkeD6yitvMtgrTU9rLD/I74rGxBmR8FR6a,iv:YC4eOP9bbbi8MFbk13+lYIcLQNW5W3l1sUSZjrKAWZg=,tag:LVvBjGcHbIhGf2kk5/GP6Q==,type:comment]
        #
        #ENC[AES256_GCM,data:U7O0AMidTMMYbG1RXIwqVSc=,iv:5VwqRMGzgHXDHYXf4ByBl90gaYvy8oAhZ634Yh/Gmeg=,tag:7ZJ0dw9JOvjKaMQAdj5x8w==,type:comment]
        #
        #ENC[AES256_GCM,data:V85WFrh9xiXkJmJbrQoFpCOwH5+GOgbQ8PWWSsYiKW8EsADijhQOASo1zmlcj1Exks8+o0pcv49LmOTd,iv:8fn87gb9P/46M11820vmOZBe0+hykDETX3Jpehk4Yzw=,tag:Mg0kVA4xl4M9TxAiily+7A==,type:comment]
        routers:
            hosts:
                cm5:
                    #ENC[AES256_GCM,data:QqqWCsy7hb4oqa0NaNGjOr4bk+6Y+bGWilq8lqNS/Q==,iv:P0edDx5bWcfxTeLBbartfLnm45HkkdZ4B9xzpuS3yzY=,tag:34JE60Qh8JkVA8svms7uVg==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:HjkSLwE1Bo8UpPk=,iv:UXFOJ85flInbdJF6m9+DvJvp8DQtrDxso4d2u+LDTbU=,tag:xyhB8bg3oxjmbFk3ElDpEw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:zpMT9A==,iv:ckr/uiQ6TiSIdWmF/b5RbMv69sGrbahJxk4W6Y4wf9s=,tag:OAeK7jmjvfNNYDxzMrUEfA==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:5t0JjSDI1N+LKfZOeIdOitw=,iv:FBXm68w7zkXVfcjN5pC6Sesb2/0b1aKOWfWqsfng6M4=,tag:l4v9lJb3FN2Z4gHD++gBFw==,type:str]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:j7awTpuie19qhAM4,iv:vCXvo2PF1Ekw8wg1ReZKd4QIcLrmMJKNOSDgIbSMaOI=,tag:dBLZ0Y+2RqjyCbUWzcZ00A==,type:str]
                    ansible_user: ENC[AES256_GCM,data:TWCEMxwoZTM=,iv:yh+5g++z8YD80gbDD3Vr0jAGJawnUdNjS3sAwk7VNsw=,tag:+JVbwqxrXnfo1qssl1cOOw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:0l1TGwM4DNXEYprFnsHLZRI=,iv:Nngy1PF0VgHrvNHpzBMw2gYlcuvfA6DxIn9WkEnx9GM=,tag:ZmX/7f0I8MIWtt8v4hGhKA==,type:str]
                    #ENC[AES256_GCM,data:V84E6B7dycxuJBwLt01jYnn6,iv:BjOJWGJjGhf5fTlwMe4PJ7kaCQrdZxT4TyglUIuXliM=,tag:DpnfLP6drAb74d+pejEJ2g==,type:comment]
                    tailscale_authkey: ENC[AES256_GCM,data:39V5c61rXX49jekqcU0JYdmt2oOPkkyjxGWxr5b3kKMOwsMVNetc/iEmvODP6mFP9A25IjiwFfieLWcXEo5pMA==,iv:4Xnqn0oERkD2b5cK/V4aE+8WHe64nTucn8l/kS9upnQ=,tag:urBfDjTEIAEstZ/fSbjsWg==,type:str]
        solo:
            hosts:
                mars:
                    ansible_host: ENC[AES256_GCM,data:bTbq9pF9QFfCKLw=,iv:RLNSzhe2R+V1xaozo19wEP7d5yoAiBkxpvN7mlZn6N0=,tag:Pz7fCGeReH7vDc0AdN07iA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:NbWIyirYG50=,iv:QLlWqdFgHHTRCbp7WcWFgyfQMcsTutUXyKeQPN/Y8iI=,tag:ANUa7EtqePCKI6i5cXX4Og==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:qZNd5I6oWl5XHeovX3kxFBA=,iv:9N0GXxHb/LNr96MFXOUZ6cBl2la6DtPEn13w9FnPgXI=,tag:7Vh011RASDlruICDnOsbcg==,type:str]
sops:
    lastmodified: "2026-01-06T10:45:27Z"
    mac: ENC[AES256_GCM,data:KpX8l5gcDWMDpq7TXdvXka1dUqbvdQeWMeRMUiwSwemj88wu2TYozp6HLFDXkNW5ELpGKZz+AtE52c5kAnoQj9lxw8KPsBb/dzjYtQBL6Pc5h8GAQLzXaKtVIdakXjPep7q13y09ADXt8gq3gJD/GHaDyY0IsDmJ6v3UBNOm3e0=,iv:dBIUzFRHjPHmnsekMyquRuXPr4syhQBelWE/Bcw8jx4=,tag:jHvTxnaWi3+IqePd0IO5pA==,type:str]
    pgp:
        - created_at: "2026-01-06T10:45:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAyrt2Mne8T94h57LZ+MRdGzCBQ8SR8waE/y7KcIzf24MZ
            GpozWq8XXglL7mOWd+dY4zPzxwy3jrFXhqxHlWQKeXeF0118YXnbZbsJ3CfmxMXr
            wbalG28P6dE726JTAwGpROx6HfVxXDEEJ49G7+NIfuyfMXd+8awVT9iAyjLeXhLc
            T1ucjVGEGiqexZADtKFzP/Vma3/bLblMerIg33kiStB6sxD3egrGAEU27VkS5yr/
            FMWXUBwI/ZTUotSKbKiLR3ABnX/XhpCMovMTmRwqgtVrhWMls/r1FDWf1O5L5R/E
            SQbEjyfBGOHe3sBnjXLRODhayjcNDaD5GlybDP95kYelJWR+RZzrpYsufbtQ1ROz
            l0+141Wjihqx/FWBP5uZy+nxTxYUMWmFMLsTnnFleAFcjasKNpspNHF8ZwYxdktf
            45elwmi9bL2ZdZN+wPIdDDNmY2XHsMYBlMu+tVMb1Qfri0oOJyj4mHTUmHD0Pnij
            Bi9pn2bdmCfXz1Ni7dtzs4ZqtxFwsCI6AF8+6ZROvR+a5/GHwVvQtvHEhhpdjnaT
            TQV5iFxuBlyC7cuB8R0aPhH0WsnGt81uYb6kA0atZT+JmawCOemQgHHJe//PJytB
            7bBYj1tOVacFrmf/gkum8dv070xAK9ayXzuhbh2TAyZ129+FSB4h0au/gGFdsyLU
            ZgEJAhBw4qZDW/dUPGUvb/zcn8oh3HZGHtUBfsBGF4w4GHcyqS1+qddsbJgC+FJi
            UY5uvcTq17HuzpGdjuMkBEJacGBvqQugSgeOEiho71fMbKEtgnPN09Sr0GdCSHuT
            Gynml7K8TA==
            =LS+s
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
