all:
    children:
        #ENC[AES256_GCM,data:8Gv2lyHP8NULdVpzLjFz9i6/wl2lfTINgWpovKH/FK9YGaXT+AFsI6l/Az3Wn21iheEbWSW8FxPqLnDB,iv:Ultkn2lvlHtdHqJm+jr5q44GOS7YzspHn2SMXGB6z4U=,tag:eKptVcMB4ZG9JyXSSUasGw==,type:comment]
        #
        #ENC[AES256_GCM,data:1TbbPnpd0Uz2LaQJjg==,iv:/2IeBOWG/c4XbHQ4X6OJqM/4+yHrKBUjndPhplgRs+I=,tag:maPZ1wKAVEtW3NcmZvNmvw==,type:comment]
        #
        #ENC[AES256_GCM,data:8NaxPoPhY3/X43u+CbaPLIdWIHji880M592wpdxkhoOkZ5Kqv5ATWTReHM/nr+HcPydFHLCRRdq4NmSY,iv:5UZortYf2Rq9ypQo2mChfjlvPyy4tBW7G44xW7VQ6Q4=,tag:v3uquneAz/9FTbPssJse8A==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:/IkTBVP08MZO9HAN2A==,iv:K8IJqHS/K+wTJpUcBarfgP949E4Lie6yNI3huNDwlws=,tag:e7TVfcT9ow7e5lePSwrnYA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:Fscg5Zwi4w8=,iv:s1HUkJhSUKpXALgWgRdWxLcw5XVatA2Dgt8wHypzwLE=,tag:h4bd4TTrbTh6U88jDAf8Kw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:hDnwMQruwxaD3u7ah3UjCDI=,iv:iFWn5akR2jXPlmZ1JJdeAjON4Z1jsd1ihyP+2vASWyk=,tag:Empg0L1QReonkH66ZlgX+Q==,type:str]
        installer:
            hosts:
                pi5-installer:
                    ansible_host: ENC[AES256_GCM,data:S/K5pPFi60i1G6cZ,iv:HnCUjKSzASRMh9JL5m2cSP3k3Py3tBk/g3C1PDQQgt4=,tag:YHwMdyXaGVYrVplK+aRUqg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:MtsyZDFMTWU=,iv:S8UjIYSl1yAqwIdU+/SMPHy+wgjW11BNcaR2XQ4e2/U=,tag:WkzLSj0dF+Rc0XQ8V6qWTg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:zCfLV1sEq/Y00xqpPcupK5M=,iv:JPGU70Y7WCK8AQkSroPvMsaCVslLGM+0jSG5nUavQqw=,tag:75Fpb5ql4cLb/s58Xtct4Q==,type:str]
        #ENC[AES256_GCM,data:t7ZvUJlphqF0pUIv2VZdzwlsoV3F0cJmlS3TMx2oq9w20e3ysIeTX2OTzNAsVse++pl2a/phgeEvrKC5,iv:3BFaL5zi+hJ4XD5X6Gdg1/Fcf+zCzjmkChph2O3ZdA8=,tag:9HaPVWC0uaBbcTfqDPkMnQ==,type:comment]
        #
        #ENC[AES256_GCM,data:swJyGuvGXaxU79ZUsK3+in4=,iv:43zFJ5/E3PR7sJMg6JhIBOd9y3GTYuRs1GF6du2lgRk=,tag:NEifAM1UA2paPdqPTAcC/Q==,type:comment]
        #
        #ENC[AES256_GCM,data:7j28lnzYK21PxOA1KbFXhZv1uoPVeDrND2Ass01aLxto1nTPcoZdLYc3R5mI7phSAx9kiRWhBx73INMH,iv:1kq2Z9FSsAGPdisRvcFxp00+saF/tjPzSKM72zObFQ8=,tag:uT+dOI6PSIIrOi7fm0gtUw==,type:comment]
        routers:
            hosts:
                cm5:
                    #ENC[AES256_GCM,data:M3tChaPZbPNEt4lziKfiMMSRFABsovvQd2k2Feo7hQ==,iv:8gx3yma08cQxA3KNz2txd9bKzjQlB2vVZU9AxrvweeY=,tag:TXSfSWt7t9q57G+yRL7+dg==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:nOmMNzRP6kjiXB6puQ==,iv:yer5JIKZTHUH/LP+ba6RpiJ5poW4XH7JCvU8cEWvYoY=,tag:J0ccFx28kzujrbkcwOOHJA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:Sbatg/p3,iv:4FvN83m9RWdOxALpE4V5BoQ0tD69b6U4S/P11nn6C+I=,tag:eIEpgEdmrEaRQnuudfFIuw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:mz+6y60w2r2m+Za1XA==,iv:tQytPif5thvn7fdi8W8oJsOV5W8fWLIia70yuwrFfM0=,tag:aDYj0zBKDdxZKo5Rwm5fAA==,type:str]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:yRdMeiup1Qt/KSw=,iv:9eFHtMuTERWetF4j3RGnYIq3TDdPP8CXD6U+E8x7Rzw=,tag:eMTYTjJqDQuEJVOO2gHYQw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:6xmuQU6j,iv:xEs+IhRaPwcke0HiP/RoQEaMEq5I2gR/7gJyzkh6UvU=,tag:lz+xVSf1Rk1q2uc6Tsz8XA==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:9sQ2hxUd9RryyBy/Ig==,iv:wRzuT3g69jjG+7xSAY/GemLk3uheifrmORZJ8OOPyWg=,tag:dTx9XQCuqMyuiwA6scmunA==,type:str]
        solo:
            hosts:
                mars:
                    ansible_host: ENC[AES256_GCM,data:Tkh3wMsNjVFD764=,iv:IMi1axNbpvscOBt4gimPK+bpSeNsinBqvdpMSajD8Wc=,tag:WguvfOXH/I+DpqlDXa3MMA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:X56mUkL5,iv:SYIqgi/LiJrtlp2tdHTb6IvYmYrvqir9QKbdZ1S1uxw=,tag:IjnbfCLeZMQzVWvzvaMiCQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:jALAI7kN/zoat4IPxQ==,iv:vLSEK6r5kOjHd5hat3lLSrCTmDaU5+1JTN7ZzQ+iuLg=,tag:+7q1eG2QZlVfyjK55Smnbw==,type:str]
sops:
    lastmodified: "2026-01-05T19:30:41Z"
    mac: ENC[AES256_GCM,data:hCZRssa6VVPu66cTtt9AwStIJtK4TovSDFn+qkXMsPNrlnNL4O1N3XQHjclP+klQaAkMR/vQSp7C0FOlWbIf+fCGHG0+IoPAo5JMy9lmyjXFsjCe/JkLYZoiB/pFItiXp+ajU4TrisUDpq+6AA5kDmLzgZa+2GPvFXUPl7eo5Ws=,iv:r4Mf8C2cciSmgllb067eeaXTW8p4Ug1AiqQAY6uThTQ=,tag:cLjyjSpeLUIelvvRZ1QHyg==,type:str]
    pgp:
        - created_at: "2026-01-05T19:30:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAy5/73c+6FAZTibz2pwzRPYFFbD/CdooboBkz4IT9L6dE
            zijgcFt+NrukKYTYmuP+JGMNirTjo4vlUHhkxrZKZvGQQJOgtTNhBQ9vkNSEX3ml
            VNETsnRiN3R4LOM4NuMT0iC8KwOPB8s1l9XN3tia3618Fjvk8+4hqoTmW/Op9qlw
            NvOFKVlVYSk2yQgl1XmDj+6CcrcHPWEI07RlC/LxOa4nIlxl0QrXuQhi7WtIG4rL
            rM1DSAc1oy1NHYoj3omq7Q1e2IWnlkUttZ8G/vr1cn7/2Zk8e87X5mIHjnwPFjsR
            /1pc/zhgVXthSQ14Phy1klP7Kd1ZHj6KX07uqXxYISYuF7gr09gCzDKDO/OiQJMd
            7DB48lcVLEMtQu8MPzmemKE09pGQzsMoPpiJsrAtWv/hkzrp6QgxqKFELt6ebGSQ
            Za0QT/KremxwbT7q8qO8vcZVPX88yx4A8BzjXdXniR5SUJQg1EdeZsT9+rY4qgj3
            aMeEZBJ/3UjHDnueUEzWhPnHFeMnpLMi5ZjUM960RE78+0AWtqUCmwGjOhuS7NP7
            NE89zmkYugSBZqrBjq7l0DH8EIcLg1JADARrv2CDsOoB3RdvUSzIM12hUd7PAfrh
            WNrdyQFLEZ3eZWywF7nUsTRXEpUMGWjsHvi72RSsYNsx4E9hkki9byBn1cIIqlnU
            ZgEJAhCCLNBOAgJAE7EFweKHadQX43IMZZRsURIM/q/Uy9KStU0MF/b/smhGVGaq
            /s8AR2bBrx/t7BmN7WLz96wuwEjQzM5pVpKkxTe6hj5AzJRq5CED1qu95iny3fJ9
            by10FmZQog==
            =mx53
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
