all:
    children:
        #ENC[AES256_GCM,data:momAQwty6SwAcGwojzWkbRCg/W1I6ZVtyk4Gn+u4THR+vAyu9nPjQ+cT+NYztO2D6NDW9iRQR00XQ419,iv:7V5WzXZFU6hADH6TnCP1z9NIHSpRhlWVJ+x+LjFbG0Y=,tag:sd60YTUkqloRQpXAp917fA==,type:comment]
        #
        #ENC[AES256_GCM,data:+tIR51Hgor9Hs9gQNQ==,iv:2i0dX5DFDlCHqzctBf+ge/zAH44ayEXmvf8lMhqpG9I=,tag:kE1M+D18UiwH0FNOkWth/Q==,type:comment]
        #
        #ENC[AES256_GCM,data:jcpm6OS3ZQSpmQ6OZaXAhxuHBkhSVULie9mDFP6uGjwuoDE/hXoMKCuekmCICwgWI4V8w2XaLq4/jTt9,iv:quge0sLkLLiZc4rLTpf1YD0qfsxeFYs+NVQUCehjRWg=,tag:AlV+2GdVz85F1fPIG+9etA==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:2OBi+fzFatk/nOvsXA==,iv:ixOhbafYItkq8wLNprBsgr/6eycA90kTyhiuBJCXXlY=,tag:wZA8sTXakRxILkQE82Uzaw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:8whokNH+d2s=,iv:dBlxq43E4zhpjb9t45vWQ0fMW4CYYriLvREGpJ1LsdA=,tag:UvdYpDSL+o26wLihspc0ww==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:XtuIV7wa8hstaRYt1pGvkUk=,iv:3lQaw8VVUa343E41ZYinpDufYe5ujf1Z+o2dVx2mzbg=,tag:fO4IqE271PUFgMNOFy2Grg==,type:str]
        routers:
            hosts:
                router:
                    #ENC[AES256_GCM,data:raw99sHwtePtgT2Nkz7rQDnYnPaGL3LCwQkX82bvYw==,iv:yh1YW073bY8B876jiJCnEni/oe0uiDRob43uKrdSUns=,tag:sol3d7mFl7YWmkiFMVRUww==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:4lUdonSIVmCjKXTDZg==,iv:7wqhUDZvLCYlludhE4enpy81GjTk5hCnPVL59LwepwA=,tag:LOeVjjgK924oItGT2UDekg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:NJShhEOU,iv:GuPSVNE8SIADuteeCFd/CksJCAUJJiqjtTF3dJGvrj8=,tag:bOIOpOb4RwzlLXi9RtC5pg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:e9R+3w3WbEidm/7nfg==,iv:YlthL3uolG8GBhGk/hpUK1hm33mYEB/jCflpc4Jelik=,tag:c30teQckmK0WJ8HTeq85eQ==,type:str]
        #ENC[AES256_GCM,data:Psv4h1vMEI7Vu8PtR6aV5TTlAqEezjvXo9/KnBD0JxvjviwpkYswoYXiNYwFXAVjo2vPaRx1Iw6mLB9H,iv:ypM1cXq6CFwous+V5ZlvNGI8khUeR578xJSne8ZAncA=,tag:lGXpVwUECrLOpsiePFJLLg==,type:comment]
        #
        #ENC[AES256_GCM,data:2FQr0/d0Gv6Z/Me/whI+Pck=,iv:EIi7QPJ7/AqWHE3FnRvGgOBnSQelMPLfnxtP4DtSVJA=,tag:mTmLCqVnJ4rNN5zgx0O8NQ==,type:comment]
        #
        #ENC[AES256_GCM,data:FzZ+ZC0YfXWxMnbj8snn+uI9H6KxLHoDMic78hMgOksE0I2IfFCOENnruyJ1VlwyQ61sNbIVf051KAo6,iv:QsTZlMC7acoiSX/ViKEtw/3LY3FdhDY5INzq6MfOJLc=,tag:y65xVMpwnu9tb4y+qv4A6A==,type:comment]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:k+Hgi9FWNCxJ3pk=,iv:uu3P1MSsA6hC4tCsWkxmwLsExMCXIt/wR3Ee2Vxq7hE=,tag:tF9myjDCab6eJpRT16NRaQ==,type:str]
                    ansible_user: ENC[AES256_GCM,data:T1QUm4sA,iv:kdmWGov9ww9gSAoQjttkYYvxKfZCoMwx8lBmNiMqJlk=,tag:p1eLlfZvYG5oA1F5bChbxw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:nGzP2JAbWgqFRkNaEg==,iv:UP5a9r2Qmco6YXoYGBFVvfDArl73EvjxbarwWBXHnZY=,tag:9miFBrz134eRFdQemBGn3A==,type:str]
        solo:
            hosts:
                solo:
                    ansible_host: ENC[AES256_GCM,data:Hgnp5jYGDwwqiUw=,iv:ZfAggeTCo8k/ZUVy5c5jrWYufQTUEOHpUnmnI/B0Lp4=,tag:QKX3r7un1UH2Wk+HC2z6Ng==,type:str]
                    ansible_user: ENC[AES256_GCM,data:nCnEH+bp,iv:btDmrtz5LFz6BRd+L+sD2wcZ67GoGydYEYBqBVsewQE=,tag:luKApAtSPofcdY9uAlH02g==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:4ADTIWyTjoYr6jfnsQ==,iv:5eQtnyRGHaC7bU9m5yv9qDprbdY6a8vcfScaOfFCso4=,tag:yi0voNYfl+XcLQ1Z9gpdag==,type:str]
sops:
    lastmodified: "2025-11-12T20:48:43Z"
    mac: ENC[AES256_GCM,data:/YTKnvMKY+NszeQnuqhmupk5TYkLFmhTg/oSs5rFJUbgPvz4cJjlkQ2kNMsMtW+ZDsaMDpXFlLcpIl92TTbdl+v90huHs4TWV37CWWoaJ2/4v2qUeVcEkq2dMJuYgaPtB0Dt7D3pVq18j96yLhB6d2PgcMinFfFtDwQflIuFmEY=,iv:ib7YP4q1/+xM+Cnxorg4WbpSxxrqJCbMMlYFx/htyyc=,tag:IVEEUP/2Gv2dS/zaClbjSg==,type:str]
    pgp:
        - created_at: "2025-11-12T20:48:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ/5AcjhrY7ug7u/oult/JYqSflFNp+fTaAqJZ9eO8iN/FX0
            e7mTSgcr3wU1zQG8NrW9HlGAODF+f3ve1NMZ8KJVh1ezjEniHiv85BSCOlJGX2eX
            5/IrqqffsmRFquiABOqYe1f2Mu/TYJHwXHhTKFD+4RFv0OfJ09QP9yMo1YxsumRl
            c6px3TBWm85B25YzCyE2sDTafXAPeP+4LtQtWwlvPuSENJMX7UPS9VcDW7OglYE6
            +Ivsc7yGQWOjHCiJA6JjNsygmgU13s61/x7FAv22xlOMlrBhizjk1n7gZlOP18Pp
            0XSUULUKZhTT42jTQDkauI4ox45KHYLfJ5zJ5nqTEi7jD9L0ZeqPWGrDegeYfpyt
            DhIMI1eYEa480pNGhljUvxuQMmGDQgEPZ3yKLpVEZqmonsyFVp5mnzwApTYZCDKG
            PKTOtNVfyuDFa1SbfmT18phRfDie8kk/BFcNeawVJvA3BFkY/wxqgZN1Go3QnA28
            Th/1zZgqQqH5SIKdgB7B8/QxuYO6kx24W74HJx8y/AGNb6xkjTu49mtQHpjVI2fc
            fmkiJH+NB4cEYqb2pbsV61BgU9bZNIJnWo5COOse7oLaHai93WBEEAW38ZILFh1C
            oS7nHD7B+gdielbAyo71HtkDSMkHQQifwAu7Un4kw8EaH9Y438X+gJNJF/Wm33zU
            aAEJAhAp7ftLweh3xuvcSTG74gumN2BtyJQ/z8u/i+cGOTd3Z2a2kVj5C4DvxtJt
            fZfMSo+JvaO9U6p58UVSf1Ma+ldFOIM2Rwn6xZF41clRU5JfjszOuJVRDQkLIIji
            QvBhRHyEhHvy
            =KwHj
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
