all:
    children:
        #ENC[AES256_GCM,data:+6Qsu76I9Zlvk0db1KXFPG6KiweN03nOydIEx1PsprXBqSO83c996hZP8J6FqmBMiH/T6F/mhJZJFd0a,iv:SBP8wjflcJi7cayfOX3yOIuFkQ5eW3+6vp18GpILJjY=,tag:QIry1z82k5fl7Vac6KrS6A==,type:comment]
        #
        #ENC[AES256_GCM,data:zSm19K3JucG943C08A==,iv:LDpzp1c1yyEXdwKQwsK70WOT1iIGudIhbQUF4DoNG6k=,tag:DJiWzPeYoKKwylgW4VXWcw==,type:comment]
        #
        #ENC[AES256_GCM,data:U8YmoWYyA0W7DrTe0CXwI3X+v1r7O+CMF0Z2LQLy7sT7icPo11Bs1CNSt+NKoxW7RK6WIrtD2RAegRcI,iv:J8ZJOzd7m5GI2ynJ3aa94Wv7aIJal32x4c7HBJFetnQ=,tag:nV1qc/3MdSqV26+LhcwiCQ==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:1DUW1DYdeOsKUe5QKg==,iv:5vKtwZO+LsXLIdpmz+sepe9tje57dNyzmjFuyKwvX44=,tag:uPsFA9XiAvPCBA80at0B7w==,type:str]
                    ansible_user: ENC[AES256_GCM,data:hZ4FhLwMX90=,iv:jbyJCaBJqclpiCGqvSPmb16SYgb1RdKV3QGs+yfjuSA=,tag:NT5AdL0JKVxrJKOpKCOjqQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:jZZUwK0aPecAz0c76Mb6jjY=,iv:g7CT9BDkC8g2EkvJJCbFi4Yz7kHMDk8UVG8JSnKzXqs=,tag:W46X2WUng/fnHJwlBj2n+Q==,type:str]
        installer:
            hosts:
                pi5-installer:
                    ansible_host: ENC[AES256_GCM,data:rbUEghgmgFgpohxY,iv:O47fniR+vNJ30KxwgJ7k+Zsbv5whoRgY3LGGm7pAazE=,tag:cql6B8+hNEuJqmZvRO2TXw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:19y7umza0Ec=,iv:voXdZmFtA5un0oNxhoruVOaQrENyai+f9ISi3XsYy+g=,tag:Sj647Q/kW8HGV8YHjrk/7A==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:1iRixiT1Ai9w2uSEwGvDHS8=,iv:xdTfF2lHb84sECzAWSAjyYdMHnb4YfvcH5uWmzAP3dg=,tag:MECGZePJA4oGquMoEqWffQ==,type:str]
        #ENC[AES256_GCM,data:/Xw4M+7OiP364S08Jv2w3w8Lqic8xixliPlIZsCyc7oS4qVGOWOal4VB8RbbdBxm+NLo9Wacwi7v4DQl,iv:AiEtytXnAyhiEW8h1UeHaJaisNTbTmfRJCLCFL+Zih4=,tag:2iNwoEihRRCfgS4cThWYSw==,type:comment]
        #
        #ENC[AES256_GCM,data:d6bz6klIgv5y7XcwCINCMoo=,iv:fM6fMs60g23+qreTjaBvCIhtq0HZZh4dNW5m8DHXJUI=,tag:FHsHLF7srBZDbr+kXnbYRQ==,type:comment]
        #
        #ENC[AES256_GCM,data:qMefU71XFD8ij9sC5Sr8aYL6+vtJT2XXR11S2kBgfvU4H+PAx9kAndToud7dn0L/wfGk34y35qsPzU0F,iv:OvXyTK61Jk6huDgPyc5nd6DP68VBdpFrgyTxRHjYZsY=,tag:zBtxoB0MBLB5BvpNx6S0Vg==,type:comment]
        routers:
            hosts:
                cm5:
                    #ENC[AES256_GCM,data:K4JbRDkf5c3bcUod8zSNUJOjAB6uZjPXfs4BGOG+tQ==,iv:ZSOpIbMQa2SEE/eQFM/eIMWTfY8A9O5S9eKt6m7iLag=,tag:qyVKJCs8bumPaDIXQHTkYA==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:3GBF/ILJAhNy4oB63A==,iv:zciJfgo32q4Qt79Vpmd5S7WrDYbevSB4zcCi8uhSiw8=,tag:ZGY1V4yXZp4pWKOlrTgyvg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:vkNvugV1y28=,iv:azsAYeiR+matQ+3rVoJNgr0ZLsdzKxNCDLVJh9g43DM=,tag:TcP1BDq0kHAgN8D4DC0HQQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:UPqTrzprrTHHTC3BHB0hF3A=,iv:Yoxst+hGyh4qbQ1XivPuG5UeFFH8qburKisl2MbZfGg=,tag:CEL1osAatJ+kKtKqndmWOg==,type:str]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:fmwOLn6ZBH8IUuUH,iv:6TjFYzRYi5YQw7qTZKbmee5N2qe3WeQe2GFOf2BW8sg=,tag:Fzmri1thm833QQDc9lSAjQ==,type:str]
                    ansible_user: ENC[AES256_GCM,data:HbTLHtWSM1k=,iv:gz98vBKuiQCL3G0dR3PBnhQ7Ak9bz6Uhc3RAjxmcWNI=,tag:btISvR8wsAKbH9fgjOM2rg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:cfYU1olZt3NfgTYhp2CQidU=,iv:onjfqkf9tkhxvUNiCgu3Fu+Q1HGBqiT8fKmD2hjoCts=,tag:QkZs4RqKbk9az81wYpAm/g==,type:str]
                    #ENC[AES256_GCM,data:rjoylu9D0xbtFouyscpDiju1,iv:ZAItmR9Bz1s1H8xFQgIqcPRWFwMAKWwXEX7KS2K6IwM=,tag:rvtUOE/T68nn4FrC6P7B3A==,type:comment]
                    tailscale_authkey: ENC[AES256_GCM,data:TYZzUtx/uLDh23Ou4XOlyYJyUjQfN9mg+k9PDm9lYJL+rKUKZK2brQFhaslQyykSDTAPy0LwnCHVkyHyfkTcOQ==,iv:kD4tf+0TR5n7xzFCfRRroAbka0mUo073O9F6NsYeNVI=,tag:1riDv9v9bzh92enTBEYXZw==,type:str]
                    tailscale_tags:
                        - ENC[AES256_GCM,data:ZH+XSHawkA==,iv:j//RChK7rHEeW6DV9NTGmmc8RrZQ7jvVDCvlxPT40vI=,tag:J6DzJv5Wzi+z7UsmXSME1A==,type:str]
        solo:
            hosts:
                mars:
                    ansible_host: ENC[AES256_GCM,data:KDI+scnsJmwvvG0=,iv:UrfsZymqO2wZL/4lX7+s2TKs1CNtKNkYMQ+C1uoEj8o=,tag:YI8aqXWeaXyc1LmaKpsczA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:Z8Oj4o1nHxw=,iv:gyCwN6Tjn9DsRuh9/Xt/LLqUkkMtoqIs5WSOtokHLhc=,tag:Btdr6NL7LpQnNrlAi26v7w==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:fB2CwRscYA8K115Y0UJ/DH8=,iv:V+1EWvUXfPrdp5nJNTBcEi2XI4GBfoJ6YuvLOfqj3vo=,tag:OHNxcH6sPpwl68iB25iy6Q==,type:str]
sops:
    lastmodified: "2026-01-05T22:01:48Z"
    mac: ENC[AES256_GCM,data:FMUg9ukehE2snp1LPfqoLcZsMS085FsjYL9HtptC4utezj9GSnVqHF5tAKqP7PVgekkjMznMry+6Ux9ocMoQzl0DYMAaTm7vqxkgV0LoC+luqf7S96hr6GzMpZDJT7TY/bUo1uFdH6K0lOc/06ANkylMOFHfDiyRU4JhumE99zs=,iv:ZBMETQN/C9+f/SXqnlGa8eTHfvjKRr2DffJBmxCBNVk=,tag:o/2OTKEXdCeOGhF8pcamMg==,type:str]
    pgp:
        - created_at: "2026-01-05T22:01:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRAQ//V3yPe+WM6pJVFjUWvK18Spm9ytKkVNX8dCIrbfYKHv42
            je02EOm5Wi+farZhddAlYmGsy5AaiKZ8XdADn3GpWCHr2Z+hCONs/g4njbX2lSZA
            zGgWjYnx49TnvoB4mMN+ZOO0fy+z4klTjdsapoZMBWDpksmVBVxHl86Nri6AzNye
            +S5HfwgkLpLGteUeTS8Cv7E9Idmvs/Tha6Bb8bMs4PWKdcErjFKF/JQAyMdo6s3d
            CE1wwDbow9dHlc5GdbNeeDrUp8n5JbXC1FSb9jZQ/jkfcOOO5mxGGxpbonRl1Ws5
            qET4S8pankReWUQ/S5KmNa1S7+u5LVfIYIQnh8QP/JkZMp3YQUK4eElPaQ6sj8hZ
            f9AcPV9FSvCoPFHGk5btyvSivgYeSouFEFux9S+NcgO8tZRHyxDn7IXV+st6e9YD
            M7LTlGWzQzfcRkScSUz8cyBFy5i1gSlujLHRKMGik93WImjQuaR2yFDxnjkuSAAq
            ZwOJ5TapT5Jebr29fBRDdIDWO+sA1nfsSMyHOik2W2t1jX2Y6dpVJyGF2j7YlXM/
            rg7LVrkVDBliYHoYxMaEcinty3sRzFH0VuxrjPTQr0EFuWlP//DwaB0x3DWFwPxJ
            4vpAOHKDhHO2puc6ORF/PRutNuq2rPnFIPD4zGSk3wDiL755wzxHIc5+mu3VJM/U
            aAEJAhBhBKnvCYkdkEQUg5kzN2WVLUoJRLqcPA3kY74300F2oCPZ5bt1q3hv0BNd
            1NegGz/5gu6y+H5hlQN/4XGARvcazxALLiWbYX4B6cYBs7peUOQROOjHvGpmdq6x
            kJpqSd1UhW8F
            =S0v/
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
