all:
    children:
        #ENC[AES256_GCM,data:jOd/jjMA9JwGHziOvSFd72Yldkbf1Ps4h4+qfyvijYuLOt3pzH1ykRjtoSltbxe4iGSsRmnK2K90YX5y,iv:YUTloULpkRQaaDm2mvc9r7J6TUvnkAW08nuBs7exECU=,tag:5V+VOXjLwr0/6xOvB7mlAQ==,type:comment]
        #
        #ENC[AES256_GCM,data:6F4iIDwvTufc672eKw==,iv:1mqwssaVkNwbMMB83GQUFm8b+oT9BZuWyiV/4QcFCQU=,tag:pEv6VGr8los30N1aDXRnjA==,type:comment]
        #
        #ENC[AES256_GCM,data:MPgswWzkIBYFbi8yEHErbqDKwK4VM/KT8yZY/9+FYS9PXNHYr0LvRacghIYJ+0Z6Hc958fI1fSdlN6oL,iv:4xTyy+2ykPsHsJ+Np0vqclP0TVfKnfbaT6Bi5rM9mPk=,tag:N/Xt3yafRtsfMRP1yFSO4w==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:6y+sL+m+PTnl/VWJLA==,iv:+AomlS0xR82xCAnK5luLJNhhqPO1QmbuEsN+eLRgYXo=,tag:u1lLuM4ZMcgsb7lflK/ubA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:IpChFVoL/R4=,iv:egTqaIicObxOx9U7iCHiUWhtUS59mgTHA6mclDR2S4o=,tag:NspI9M03RjuZebZ+QOhTgQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:sd9OWIZX3svYxrFHvOLeGZA=,iv:sW9W1bM6iwVmUPPfMDaTi7j5sNng2T/u6Fsx1aw81vc=,tag:x0oF0IUpWdhT8NIbgJ3f1g==,type:str]
        installer-stage1:
            hosts:
                pi5-installer-s1:
                    ansible_host: ENC[AES256_GCM,data:bX1dG5tyfcmjB48jnQ==,iv:kOoLSApyBK2mTP9DrfkecXnmmH2m+CpgsuDDVhCae0k=,tag:qXpcZZFXlFAPaUVrIG9h4g==,type:str]
                    ansible_user: ENC[AES256_GCM,data:PT7f+gZW+V8=,iv:rZk2e9wVnfq7Mqj9aMRKc/G9ZWlbwkPb5i+AThHJPMw=,tag:BheB/90U14T7DEFWdnksIQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:s+iJLgPDopXvoL7UDeEMTyI=,iv:p+cqQ6tR7utZmUUeyEatwaY0n7rOm3IClJrdkO68Lng=,tag:SsaieU5JWXq36myKFXVbbw==,type:str]
        installer-stage2:
            hosts:
                pi5-installer-s2:
                    ansible_host: ENC[AES256_GCM,data:MwCpKPaPitkByNSd,iv:aFjaxALeMbgb6LwTnHqS5Yu9P4QaTJZ8WykyCqm6zQk=,tag:k+BLOJSsn6sg+ZeNQIH3CA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:4uMH8wT5jyo=,iv:3Gd43KP76qFLjEjFLv9ElqFIAE8ZtL96T4hCcQSe7rY=,tag:BaAQa+1VvKLD9kfAvCzbTw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:0NAZUqR8wdvfpVRgRkYgmx4=,iv:+U592tQAMhlvfqHyCI9So5q9BR1Q0dBsjjuAbDnrNy0=,tag:YbLAFeA1DNjSQXIMDYe5Sg==,type:str]
                    tailscale_authkey: ENC[AES256_GCM,data:Hqj3ifnGEiI6hfsmm9L/By1vcDQZKEQU1/ecAqNOkHUTqxldTqNnhSIZy8NDB0Aiib5u2q6K4OZbGZyKJGM=,iv:Txu0zzI9RZ4dq/17/HZftr9qS84+0UA4BDkVHlmJlus=,tag:hyqnXfsxmUxb3+vA++sy8Q==,type:str]
        #ENC[AES256_GCM,data:l7BT1xMc/dDRuO0TOyeEBMdZmRdeDsyfAcxn8yXAtiui2jmxLG9KN/OnaBdcyIv+956jjfKwWKtC/7gc,iv:/XYdlkrrPTNkc1MjKjXD8TXkSgKtjU8UFQgsZn79mfw=,tag:+OL5ZbrySMCWS4DaqLum5Q==,type:comment]
        #
        #ENC[AES256_GCM,data:B1xIhGZngjhBBikNpQx2+uw=,iv:l3UYsXPNm7T2mrPHtuEYE/5B9e9kWqgSBfODKklxBb8=,tag:CM3eT5VYpFHLrBCPnU9h7w==,type:comment]
        #
        #ENC[AES256_GCM,data:KZ3Vp/X/9Q96AUiPCp70CnDNFcC6Em8Bo3sJcPjmOaN8FywDu03RxKLAcz9C4NQoulwoMQhWmrydtpBU,iv:hO5v5glOmkhQOYOXCvIjKhZLjobLrTnpGqsYK1Hf9Iw=,tag:4Hw7+fRyWzSphd3AH86VJA==,type:comment]
        routers:
            hosts:
                cm5:
                    #ENC[AES256_GCM,data:MYiIfJSDlJxq/xDF3ZS4fk7bO2jH6K13+bN52I8xyA==,iv:yLDSz4hYUQzEvHnOYfqkc1zPbMsV9A79SjCvqhDBez0=,tag:/PWhExYz9rjEa3X+u7cDnQ==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:dAhtSDQGam65NAo=,iv:TOAOM+ykT8i+aL6fC0EsyeBM83ET9KocAxY2hPodHXM=,tag:ddV6PS/q83xwfc/du9VsUQ==,type:str]
                    ansible_user: ENC[AES256_GCM,data:OD+TNw==,iv:tfbKpIL8pOZxfRPfHEWnDKModMilPuCeHD2QZxCOjXE=,tag:FRNNxJuoIF7iOFGgqnmaOg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:mogSNg8dcZHUqtCk/O24g5c=,iv:iC2Jl5GiVYX950z2a67ca4C3++ziSLjYKYcvt0b9HwU=,tag:r9OOmISku4FuD+upwiGARg==,type:str]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:nP/7JLx0RLWZZ6uI,iv:BCURw/wFZZFP+96HZodEjeEPoHYCjwKgd8SVyccUq+I=,tag:U3B94EYD5qHWUwfToFVzVA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:rrd3c0dxSSg=,iv:Qz/G1QKFCDewh4jOB1CygNAaduLfCIsZGebe49xNvhs=,tag:kVMApSY03IugcfGLGLrXgw==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:nV7ZjbHzXWBbO2VxEy2pe88=,iv:Hd/XAMSChGl7QAnR7uPZmEJn3xNmV3wADIYT0BxC848=,tag:ecVJPgbdksqStnw/NCps6w==,type:str]
        solo:
            hosts:
                mars:
                    ansible_host: ENC[AES256_GCM,data:vuZtA6gGNCL6tyrO,iv:k+mXH5sRkSMSpX0NfwmHzfLHtLtL7ofq/yR3PWy9Bzg=,tag:K8h99nQ5ERbiONI03GzVrA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:bVDrxftDDYg=,iv:7eW8nHUmTuo4IdoezokYaYC9wcGrWLb/sv4qS/AdThA=,tag:wk08z7pHKJthucAFmJZLog==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:uo37jIYZfQgwcZYub04sTGA=,iv:tBGzWrfVOslSS4yN2EsSng8emLXtaYDUDww55TV2Y94=,tag:Y0r2TrgqCeiGQN2QyfV0qA==,type:str]
sops:
    lastmodified: "2026-01-06T21:25:17Z"
    mac: ENC[AES256_GCM,data:u0i8C5PFz/6wtw83NegAeGBAjGFy0sLS2VvTGDhrHq69eAG/XPzmS3nCZJsPPa7Ifn/8xdIBr2/7Ol2T1nhmYC1raCTXwGyiYrx+rNpnZ3TuswVfkkwInf0VDT2OT4bvIZLxHYYAju9NgoK9U7JLFAtgWACXGrs0LdYuY+RbG9U=,iv:mukFiRksLYJmyEzeSePEbtVUvEl2jJZtrx6ul4zCrqM=,tag:J6xhKwIeslKLq4VN5Ar7Xw==,type:str]
    pgp:
        - created_at: "2026-01-06T21:25:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAAlyjR2GoyVojlPFni4pfyEf3OA9L5JCzm+/28U0TUQf6g
            73AYbGyuHNu0+yDfcY9zEuTYS66jmiRE9+DXlF3amfmlQ8WOjW26WOTzKuDzAJxN
            LjjmVCE6tgMiVQmff6xRbr9z+N4lFIiOkkRQGIWkurd2O/5qEEOi1JxRH3ArIZzF
            4w7aX2mkYWSiaT0dcPQk1tO54XBFxdmfeQtIuq3mqePMML5RTSGsfzfbIHFzoAD9
            P0f8tvxJHiKInx0m7NHTAl/FrxUHUdupc5pdcDQmSrruE5aZ6CzAaaIxz8sEC+WO
            C6sZ9RF52npgaWTdeQCzay8Bp4P6E3RlgKYfOadZ53mVc0OQfs4yEATsSbmWHiAm
            2BHigX7fR+NNaNYTUgZWDdFQuLoT6RrMzdtekPQrB5JXaCooAjxnk49Ya9yKZ6fn
            2t8AMjYqJGRhgdAEZQcRCxZGFbaArP0RMzRGAQla64xQt4rTDw6Yp1hgMFRvlJLc
            o6KwEM8lcRbqht7NyKR5zxZYeN4r1cRREgzsyfnA5qdvJC/Xl+miGc11Dp8bdSI4
            JsTVA2acwbgl6+1qCP3GXgS4PjH/O/TA71Fcn7xVLb25pwysBJ9RYsO8jUqxbrF6
            Q2ZS4SEBQIgS576YxGTl/G8qeFUD1ejGec6HKilhQ25DLIvaRWyg94BmXbT6fXbU
            ZgEJAhBb8fTtL16J4rzFTMYmtGxXop9iRIrpaGQVc8HEA/uBonOaf0g4l9XEA7UP
            HOGENx8WPaDJjO7wYTeTJybvlmFjCmIKLi3MBGJWNG96YN+RZFnFDdXBtDPZPxQ1
            FJtNGmzKPw==
            =PE5+
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
