all:
    children:
        #ENC[AES256_GCM,data:JxpGB9RMRrPeDIM/xl7MVvt4zIgE0+gn6LzG8+9WaCIZEk9E9CP/EY4PCVlQyDe7eiD1nR9Ax3mKZIqT,iv:tIcz8uV82RtDvzgWlFbLK3uRq3thCj2E4is+OxYy/70=,tag:azNbZsgQY9O0RdRoXvWqGQ==,type:comment]
        #
        #ENC[AES256_GCM,data:zJkYGXwhl3SVfAaSHg==,iv:m9aGKEs0y0Zu+QhtbJdw6jSmW3yFQODGciP17syCWqY=,tag:gvSYX+94jB/Kdrvw1B+GQA==,type:comment]
        #
        #ENC[AES256_GCM,data:aUOtxvH5n/1CqbIiBmMdoqQy8XVL7bm2vZaptTnk1iXmQuzmrJbGdE871AU79c13ZogXryCtAm3JoPUv,iv:9QMnydw2/iCXUS30Zt5dvKnsLIUZoT/m/hjCKEjwpEQ=,tag:BCD4r+ltbD86NzXPTXPk6w==,type:comment]
        builders:
            hosts:
                builder1:
                    ansible_host: ENC[AES256_GCM,data:PBLVtgaPqtonL6NdgQ==,iv:vyHlD9Pp+2FkuW59dbPmGKTwXAI8dkDdOCkblK2TJbw=,tag:91D8tqcx3zzAY+QEhVddQg==,type:str]
                    ansible_user: ENC[AES256_GCM,data:iIuxwcJQ0vY=,iv:geBTWJqcYx+CH2GX3ABjx5eFiD7usjJFC5dFDpYs+7o=,tag:XIZgtMxtp+Vz3aCjg83KTg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:XcmGQj4B/GcwfeKW1Da9DeA=,iv:Bsl/slIXto9HfSry55pqJQpNqdBuNbHlZgPk7+BEDmY=,tag:3LspZcpOJK8vGDsvIHiDcA==,type:str]
        routers:
            hosts:
                router:
                    #ENC[AES256_GCM,data:OE2MZzVpeTiKlkNkXsvaSObba0KudeJ8nmtUh+4qjw==,iv:5QNOcO2Hzdl2ekiSIYGBnxfkDzuJYdslqYnE2lHHRjc=,tag:Slp+3MkBY9nkfCGTmIdUYA==,type:comment]
                    ansible_host: ENC[AES256_GCM,data:f3fnky6v13Ksxs+wVw==,iv:2Ia8D+4prOc8cYGR/zXc0c7FRXQX4E6LGQzSNA58phM=,tag:Xuo0CUKwzzPN6o0WlVIZMw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:yYbNiZvb,iv:EjqbrzZVvK0//CBzo6oHwLA2Ll9LTxzC02wyXMnQyd4=,tag:Qhq4I06llCLxDXIQCKDgCQ==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:W87Su0ASyhKUVOhnrA==,iv:PtVyKA9HLE9CCMcYBUAGha/jxPE8dDygymiu7VUxcFU=,tag:5IICOm6IlOcD/ip4LQzazg==,type:str]
        #ENC[AES256_GCM,data:Gx/3fL1ZXisLYVS4NAb1aSPzhHjI4WXX0oqOlVJ9KSJFtZIz1XhYLEDO+h5mu4XXEI0r+wzP9nE5Nt3Z,iv:0x6/efK0eK+tat0R1pbyJ6EgarfMA6Q4EkY+JXG6dX0=,tag:D9zPga8bNSMVkSGe2yfefA==,type:comment]
        #
        #ENC[AES256_GCM,data:fTO3NJFFLFkc+o6xbc5Ylw4=,iv:Ho6b1eRwnD3Kg8dy0DgaPwkDA/kZyMKfIbQppqhtA8U=,tag:Wm5xa85DIyWGhzOEknH8FA==,type:comment]
        #
        #ENC[AES256_GCM,data:rmeqSLKZ6KvKXAo/51Gdo49Z+3fhhxh2LAZ4/StVmae6GiPhEioZxlG2n1flnB4QiIx8lwwiUQUrWheV,iv:xd0ZjtoPN+iWrSP2oy07q2g7sGEttTnqUutjWzssnCM=,tag:CqZ1uWEB0ENUaeISYCAAPA==,type:comment]
        pi:
            hosts:
                pi5:
                    ansible_host: ENC[AES256_GCM,data:6Y07Xmpc/mSCgjU=,iv:OU7Mg5pMKZV2FJC4SnyWNvtDul9CN/Bacy1v45+OLe8=,tag:8RruqeZH6JzH4zj3+HDFpw==,type:str]
                    ansible_user: ENC[AES256_GCM,data:P+zHQ3hD,iv:OxL0jvo/cLuFnEjqBP3z9a4ezQoyJHj/Ap29X5TBj14=,tag:kEqfK7asirrGfAUOSWd98A==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:kJD/w5Tt37aldcJXdA==,iv:iCvkuL9Mc/2ni4G5hZ/N1aM7VIcaNvPtn6jHI7k1Z8g=,tag:AiPSckj/zqx9ovrepngcDg==,type:str]
        solo:
            hosts:
                solo:
                    ansible_host: ENC[AES256_GCM,data:BwmyrQGEc5n9CGM=,iv:a7L+KzccQGFfz1XRORsENoRJstA/8W+UhJzUlY/9oVM=,tag:JHTb8sKVEeq28zO2kBovlA==,type:str]
                    ansible_user: ENC[AES256_GCM,data:UtuwrtHy,iv:c4Zomj2/41zZKXd7CG0scMN2kN5AZhR8BeIF/iC04Uc=,tag:z6yFdgTUhbkLeR+zCbQPkg==,type:str]
                    ansible_ssh_private_key_file: ENC[AES256_GCM,data:esdd3wWUoFHrAEu5qg==,iv:AV0ejHmULJpUU4LYff9IgKzjtTQUdoB7Saa7OIco0Uw=,tag:Vgu9952NvfhUgK2l22txZA==,type:str]
sops:
    lastmodified: "2025-11-23T10:00:34Z"
    mac: ENC[AES256_GCM,data:CWsBrZJndkKmOf38xB7AdBxTiZXjdtaQLuACYllJNtHcrb8rSkKV8V35g8qZBUivRi+tAh2S8zkULcW1WfYZ7Z4S1GERr01gKo2nzZ5mKp7Mj6ZGJJ96QVuBd1BCHLtZ1VIWS/C0k4hz9DS2NMEV4YUjcwa43mBVc9J/OZCPxJ4=,iv:JsHa+lm2UP2GIH1+Ktv+juZOHZq5T30POr77xZpWMWA=,tag:MoldK1L1NTyjjJNkhmRJYA==,type:str]
    pgp:
        - created_at: "2025-11-23T10:00:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2aYMUUzTqIRARAA2qhyR+5KKPou3IdeB4wwRd+IHSHXpZK63CvriNvHq8NV
            FFfn3bq9A1c737kZ1oyknUduFXJZX0SG56Ny02ZxILQuwnge2SFsrvM0xSGZhlOW
            UGA+28fLrcT3sDMPxccMYypgcsH71l2oRld3474VNutn/8uV35ydiuJuYbuIfUEw
            HozU33i/nBqfW9Nj2TjgW+np0LMGIc3Tu+x09LpBAZyPJwEwjw4FyFiZUifQe5QK
            BYQfTPF+jHxkIitAHd8diIQuZCx4S82SbIy+rgNfnsGXVClWQ/G5D+MwS+WRXKd7
            S20co7OAo2SY/Td4UHMjPnv513phyxr6/HbfC0vrjrZLWaTvfAs0cZGIRAUR2Df5
            znvOIPY4C3l6GP+mY0uDnAOpEaPSPewH+N4BfUxfE9HmkU/EG2gVB8oC07mfevxq
            Ugu6MFiawRhubv4VdcNjAh9nZaxa3YgNMHa0HUH3D6l0TVRl54R+jf6082Gygp/A
            s5YmQkz18tJcjqQdD0z67PJiTpCmNxmoinqVO6KuKiMpUVC35dM6EG20kqt4M0wS
            jiBZD8bGno34G+oAubLhQdLq/+ieoGs8+WVcLcqNqy0GNzOPeGGN89C3FFcDbQFJ
            2lO11OHNPESzM8opIrVuvVXj5O2sEWhhT1OD6l8+LUV9He0q6nPNlqfnEdYZ4+fU
            aAEJAhAHEzJ5jvt0AtsZRRKv03XXLzbhtCrZCqW5szgnRz/yNF3NWq7n0R8/ND5v
            QrSjgafkJjZEg3Vi1gohB2/0GNbj1u63KoECB/3kV3DzfoBkWNqEcwGyX4h0r45W
            ysPlcdzD56d2
            =pqsR
            -----END PGP MESSAGE-----
          fp: 4C8C1857C468123F57E5C7E7A05D361B64156AA7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
